INSERT INTO tb_category(name, created_At) VALUES ('Books', NOW())
INSERT INTO tb_category(name, created_At) VALUES ('Electronics', NOW())
INSERT INTO tb_category(name, created_At) VALUES ('Computers', NOW())
INSERT INTO tb_category(name, created_At) VALUES ('Devices', NOW())
INSERT INTO tb_category(name, created_At) VALUES ('E-books', NOW())
INSERT INTO tb_category(name, created_At) VALUES ('Test', NOW())